# Python CI - Lint, Type-Check, Test
# Copy to: .github/workflows/ci-python.yml
#
# Triggers on pushes to main and all pull requests.
# Tests against Python 3.11 and 3.12.
# Uses Ruff for fast linting and pytest for testing.

name: CI - Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint & Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Customize: change Python versions here
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint with Ruff
        run: ruff check . --output-format=github
        continue-on-error: true
        # Remove continue-on-error once your code is lint-clean

      - name: Type check with mypy
        run: mypy . --ignore-missing-imports || true
        # Remove || true once your types are clean

      - name: Test with pytest
        run: pytest --tb=short -q || true
        # Remove || true once you have passing tests
