# TypeScript CI - Lint, Type-Check, Build, Test
# Copy to: .github/workflows/ci-typescript.yml
#
# Triggers on pushes to main and all pull requests.
# Tests against Node 20 and 22.
# Caches node_modules for fast reruns.

name: CI - TypeScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint, Type-Check & Build (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Customize: change Node versions here
        node-version: [20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: npx tsc --noEmit --pretty || true
        # Note: using || true so type errors don't block builds.
        # Remove || true once your types are clean.

      - name: Build
        run: npm run build

      - name: Test
        run: npm test --if-present
